# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0002_auto_20200123_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
