# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-03 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favourites', '0003_auto_20200129_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourites',
            options={},
        ),
        migrations.AddField(
            model_name='favourites',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
