# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-04 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0004_auto_20200203_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
