# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-12 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0007_favourites_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='favourite',
        ),
    ]
