# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-12 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.CharField(choices=[('Rolex', 'Rolex'), ('Timex', 'Timex'), ('Ted Baker', 'Ted Baker'), ('Tissot', 'Tissot'), ('Michael Kors', 'Michael Kors'), ('Lacoste', 'Lacoste'), ('Lotus', 'Lotus'), ('Hugo', 'Hugo'), ('Gucci', 'Gucci'), ('Diesel', 'Diesel')], default='Rolex', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mens Watches', 'Mens Watches'), ('Ladies Watches', 'Ladies Watches'), ('Kids Watches', 'Kids Watches')], default='Rolex', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
