# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='topbrands',
            field=models.BooleanField(default=False),
        ),
    ]
